spring:
  application:
    name: mydevlog
  datasource:
    url: jdbc:mysql://localhost:3306/mydevlog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
media:
  storage:
    root: ${MEDIA_ROOT:/tmp/mydevlog}
    publicBaseUrl: ${MEDIA_PUBLIC_BASE:https://example.com/files}
  limits:
    maxBytes: 5242880
  allowedMime:
    - image/jpeg
    - image/png
    - image/webp

logging:
  level:
    org.jetbrains.exposed: INFO